### ISSUE TITLE
[Bug]: Stops working when used in chat textarea

### ISSUE THREAD

**Issue by gavinhewitt** [TangoDev-it/filament-emoji-picker#2]
### What happened?

Hi, first of all thank you for this plugin!

I may be using it as not intended, but I'm attaching it to a chat textarea. It works perfectly, the emoji is inserted into the textarea. However, if you click the 'open popup' button a second time the console displays this error:

![image](https://github.com/user-attachments/assets/b65e859e-6782-42fb-afe0-b6c5d485f6d2)

Any idea what could be causing it?

### How to reproduce the bug

See above

### Package Version

latest

### PHP Version

8.3

### Laravel Version

11

### Which operating systems does with happen with?

macOS

**Comment by manugando** [comment]
Hi! Thanks for reporting the issue, can you please provide the code that you use to initialize the textarea with the emoji picker? Thanks!

**Comment by jeffrey-betrnk** [comment]
I had the same issue. This is my sample code. 

                        Forms\Components\Textarea::make('message')
                            ->hintAction(EmojiPickerAction::make('emoji-messagge'))
                            ->label('Text Message')
                            ->columnSpanFull()
                            ->rows(8),

**Comment by jeffrey-betrnk** [comment]
@manugando It works. Thank you so much

**Comment by manugando** [comment]
@gavinhewitt could you try to update to the latest version (1.0.3) to see if your issue is solved too? Thanks!

**Comment by gavinhewitt** [comment]
> @gavinhewitt could you try to update to the latest version (1.0.3) to see if your issue is solved too? Thanks!

Thank you so much! I'm on holiday with a really sucky connection :( I'll report back when I have better access!

**Comment by gavinhewitt** [comment]
@manugando Thank you, works!

**Comment by gavinhewitt** [comment]
@manugando Thank you, works!
