### ISSUE TITLE
[Bug]: Don't work when use lazy() or live() on Input

### ISSUE THREAD

**Issue by luluxe** [TangoDev-it/filament-emoji-picker#3]
### What happened?

Hello,

The emoji select don't work when use lazy() or live() on Input.
It work the first time you click on it, but the second i have this error in console :

filament-emoji-picker-scripts.js?v=1.0.2.0:4 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'classList')
    at HTMLDocument.ni (filament-emoji-picker-scripts.js?v=1.0.2.0:4:13987)
    at Function.dispatch2 (livewire.js?id=cc800bf4:1388:8)
    at eval (eval at safeAsyncFunction (livewire.js?id=cc800bf4:1176:21), <anonymous>:3:56)
    at livewire.js?id=cc800bf4:807:11

### How to reproduce the bug

- Create TextInput lazy() or live() with EmojiSelector
- First time to click on emoji, it work
- Second time, it bug

### Package Version

latest

### PHP Version

8.2

### Laravel Version

11

**Comment by manugando** [comment]
Hi! Thanks for reporting the issue, I'll look into it and let you know 👍

**Comment by manugando** [comment]
Hi @luluxe , the issue has been solved in the latest version (1.0.3) ✌️

**Comment by luluxe** [comment]
Thank you for your speed 👍
